export const ADD_TODO = "ADD_TODO";
// get req
export const GET_TODO_REQUEST = "GET_TODO_REQUEST";
export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS";
export const GET_TODO_FAILIER = "GET_TODO_FAILIER";

// post req
export const ADD_TODO_REQUEST = "ADD_TODO_REQUEST";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_FAILIER = "ADD_TODO_FAILIER";
// get selected todo req as per ID
export const GET_SELCTED_TODO_REQUEST = "GET_SELCTED_TODO_REQUEST";
export const GET_SELCTED_TODO_SUCCESS = "GET_SELCTED_TODO_SUCCESS";
export const GET_SELCTED_TODO_FAILIER = "GET_SELCTED_TODO_FAILIER";
// remove selected todo
export const REMOVE_SELCTED_TODO_REQUEST = "REMOVE_SELCTED_TODO_REQUEST";
export const REMOVE_SELCTED_TODO_SUCCESS = "REMOVE_SELCTED_TODO_SUCCESS";
export const REMOVE_SELCTED_TODO_FAILIER = "REMOVE_SELCTED_TODO_FAILIER";
// toggle selected todo
export const TOGGLE_SELCTED_TODO_REQUEST = "TOGGLE_SELCTED_TODO_REQUEST";
export const TOGGLE_SELCTED_TODO_SUCCESS = "TOGGLE_SELCTED_TODO_SUCCESS";
export const TOGGLE_SELCTED_TODO_FAILIER = "TOGGLE_SELCTED_TODO_FAILIER";
// update selected todo
export const UPDATE_SELCTED_TODO_REQUEST = "UPDATE_SELCTED_TODO_REQUEST";
export const UPDATE_SELCTED_TODO_SUCCESS = "UPDATE_SELCTED_TODO_SUCCESS";
export const UPDATE_SELCTED_TODO_FAILIER = "UPDATE_SELCTED_TODO_FAILIER";

// completed todo
export const COMPLETED_TODO = "COMPLETED_TODO";

// total todo
export const TOTAL_TODO = "TOTAL_TODO";
